# Generated by Django 4.2.29 on 2026-03-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('property_type', models.CharField(choices=[('house', 'Nhà ở'), ('apartment', 'Căn hộ'), ('land', 'Đất nền'), ('villa', 'Biệt thự'), ('office', 'Văn phòng'), ('shophouse', 'Nhà phố thương mại')], max_length=20, verbose_name='Loại BĐS')),
                ('listing_type', models.CharField(choices=[('sale', 'Bán'), ('rent', 'Cho thuê')], max_length=10, verbose_name='Hình thức')),
                ('status', models.CharField(choices=[('available', 'Còn trống'), ('sold', 'Đã bán'), ('rented', 'Đã cho thuê'), ('pending', 'Đang chờ')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá (VNĐ)')),
                ('price_unit', models.CharField(default='VND', max_length=20, verbose_name='Đơn vị tiền tệ')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diện tích (m²)')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Số phòng ngủ')),
                ('bathrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Số phòng tắm')),
                ('floors', models.PositiveSmallIntegerField(default=1, verbose_name='Số tầng')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ cụ thể')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('has_parking', models.BooleanField(default=False, verbose_name='Có chỗ đậu xe')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Có hồ bơi')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Có sân vườn')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Có nội thất')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'Bất động sản',
                'verbose_name_plural': 'Bất động sản',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu thích',
                'unique_together': {('user', 'property')},
            },
        ),
    ]
