# Generated by Django 4.2.29 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='province',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số phòng tắm'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số phòng ngủ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số tầng'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Bán'), ('rent', 'Cho thuê')], default='sale', max_length=10, verbose_name='Hình thức'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Nhà ở'), ('apartment', 'Căn hộ'), ('land', 'Đất nền'), ('villa', 'Biệt thự'), ('other', 'Khác')], default='house', max_length=20, verbose_name='Loại BĐS'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Không hoạt động'), ('sold', 'Đã bán'), ('rented', 'Đã cho thuê')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường/Xã'),
        ),
    ]
