# Generated by Django 4.2.30 on 2026-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_province_property_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hướng'),
        ),
        migrations.AddField(
            model_name='property',
            name='furniture_status',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tình trạng nội thất'),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_status',
            field=models.CharField(blank=True, max_length=120, verbose_name='Pháp lý'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_details',
            field=models.CharField(blank=True, max_length=120, verbose_name='Thông tin đỗ xe'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm xây dựng'),
        ),
    ]
