# Generated by Django 4.2.30 on 2026-05-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_facing_property_furniture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='Lịch rảnh xem nhà'),
        ),
    ]
