"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')
_default_secret_key = 'dev-only-change-me'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', _default_secret_key)

if not DEBUG and SECRET_KEY == _default_secret_key:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False."
    )

# SECURITY WARNING: don't run with debug turned on in production!
_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(',') if host.strip()]
if not ALLOWED_HOSTS:
    if DEBUG:
        # Safe local defaults so runserver/swagger work without manual env setup.
        ALLOWED_HOSTS = [
            "localhost",
            "127.0.0.1",
        ]
    else:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG=False."
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',                              # ← THÊM
    'rest_framework',
    'rest_framework_simplejwt',                 # ← THÊM
    'rest_framework_simplejwt.token_blacklist', # ← THÊM
    'drf_yasg',
    'django_filters',                           # ← THÊM
    'accounts',
    'agents',
    'properties',
    'appointments',
    'news',
    'prediction',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← THÊM, phải ĐẦU TIÊN
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _parse_database_url(database_url: str) -> dict:
    parsed = urlparse(database_url)
    engine_map = {
        'postgres': 'django.db.backends.postgresql',
        'postgresql': 'django.db.backends.postgresql',
        'pgsql': 'django.db.backends.postgresql',
        'mysql': 'django.db.backends.mysql',
        'sqlite': 'django.db.backends.sqlite3',
    }

    if parsed.scheme not in engine_map:
        raise ImproperlyConfigured(
            f"Unsupported database URL scheme: {parsed.scheme}"
        )

    engine = engine_map[parsed.scheme]

    if engine == 'django.db.backends.sqlite3':
        return {
            'ENGINE': engine,
            'NAME': unquote(parsed.path.lstrip('/')) or str(BASE_DIR / 'db.sqlite3'),
        }

    config = {
        'ENGINE': engine,
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ('5432' if engine == 'django.db.backends.postgresql' else '3306')),
    }

    if engine == 'django.db.backends.postgresql':
        _pg_options = {
            'sslmode': os.getenv('HSW_DB_SSLMODE', 'require'),
        }
        _pg_search_path = os.getenv('HSW_DB_SEARCH_PATH', '').strip()
        if _pg_search_path:
            _pg_options['options'] = f"-c search_path={_pg_search_path}"
        config['OPTIONS'] = _pg_options

    return config


_database_url = os.getenv('HSW_DATABASE_URL', os.getenv('DATABASE_URL', '')).strip()

if _database_url:
    DATABASES = {
        'default': _parse_database_url(_database_url),
    }
else:
    _db_engine = os.getenv('HSW_DB_ENGINE', os.getenv('DB_ENGINE', 'django.db.backends.mysql')).strip()

    if _db_engine == 'django.db.backends.sqlite3':
        DATABASES = {
            'default': {
                'ENGINE': _db_engine,
                'NAME': os.getenv('HSW_DB_NAME', str(BASE_DIR / 'db.sqlite3')),
            }
        }
    else:
        _db_defaults = {
            'django.db.backends.postgresql': {
                'NAME': 'postgres',
                'USER': 'postgres',
                'HOST': 'localhost',
                'PORT': '5432',
            },
            'django.db.backends.mysql': {
                'NAME': 'housesell_db',
                'USER': 'root',
                'HOST': 'localhost',
                'PORT': '3306',
            },
        }
        _selected_defaults = _db_defaults.get(_db_engine, _db_defaults['django.db.backends.mysql'])

        DATABASES = {
            'default': {
                'ENGINE': _db_engine,
                'NAME': os.getenv('HSW_DB_NAME', os.getenv('DB_NAME', _selected_defaults['NAME'])),
                # Use project-scoped vars first to avoid collisions with global OS vars.
                'USER': os.getenv('HSW_DB_USER', _selected_defaults['USER']),
                'PASSWORD': os.getenv('HSW_DB_PASSWORD', ''),
                'HOST': os.getenv('HSW_DB_HOST', _selected_defaults['HOST']),
                'PORT': os.getenv('HSW_DB_PORT', _selected_defaults['PORT']),
            }
        }

        if _db_engine == 'django.db.backends.postgresql':
            _pg_options = {
                'sslmode': os.getenv('HSW_DB_SSLMODE', 'require'),
            }
            _pg_search_path = os.getenv('HSW_DB_SEARCH_PATH', '').strip()
            if _pg_search_path:
                _pg_options['options'] = f"-c search_path={_pg_search_path}"
            DATABASES['default']['OPTIONS'] = _pg_options

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # ← THÊM để Swagger nhận JWT/Session từ Admin
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', '1800'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/admin/login/'

from datetime import timedelta

# CORS - Cho phép FE (React) gọi API
_default_dev_cors_origins = ','.join([
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:4173',
    'http://127.0.0.1:4173',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
])
_cors_allowed_origins = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    _default_dev_cors_origins
)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_allowed_origins.split(',') if origin.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _cors_allowed_origins.split(',') if origin.strip()]

_cors_allowed_origin_regexes = os.getenv('CORS_ALLOWED_ORIGIN_REGEXES', '')
CORS_ALLOWED_ORIGIN_REGEXES = [
    pattern.strip() for pattern in _cors_allowed_origin_regexes.split(',') if pattern.strip()
]

if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES.extend([
        r"^http://192\.168\.\d+\.\d+:(3000|4173|5173|8080)$",
        r"^http://10\.\d+\.\d+\.\d+:(3000|4173|5173|8080)$",
        r"^http://172\.(1[6-9]|2\d|3[0-1])\.\d+\.\d+:(3000|4173|5173|8080)$",
    ])

FRONTEND_BASE_URL = os.getenv(
    'FRONTEND_BASE_URL',
    CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else 'http://localhost:8080'
).rstrip('/')

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@bluesky.local')

SWAGGER_PUBLIC = os.getenv('SWAGGER_PUBLIC', 'true' if DEBUG else 'false').lower() in ('1', 'true', 'yes')

# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Media files (ảnh upload)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPABASE_URL = os.getenv('SUPABASE_URL', '').strip()
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '').strip()
SUPABASE_AVATARS_BUCKET = os.getenv('SUPABASE_AVATARS_BUCKET', 'avatars').strip() or 'avatars'
SUPABASE_PROPERTY_IMAGES_BUCKET = os.getenv('SUPABASE_PROPERTY_IMAGES_BUCKET', 'property-images').strip() or 'property-images'
SUPABASE_VERIFICATION_DOCS_BUCKET = os.getenv('SUPABASE_VERIFICATION_DOCS_BUCKET', 'verification-docs').strip() or 'verification-docs'
SUPABASE_NEWS_BUCKET = os.getenv('SUPABASE_NEWS_BUCKET', SUPABASE_PROPERTY_IMAGES_BUCKET).strip() or SUPABASE_PROPERTY_IMAGES_BUCKET
SUPABASE_SIGNED_URL_EXPIRES_IN = int(os.getenv('SUPABASE_SIGNED_URL_EXPIRES_IN', '3600'))

# Property media upload policy (V8)
_property_image_allowed_types = os.getenv(
    'PROPERTY_IMAGE_ALLOWED_TYPES',
    'image/jpeg,image/png,image/webp,image/gif'
)
PROPERTY_IMAGE_ALLOWED_TYPES = {
    item.strip().lower() for item in _property_image_allowed_types.split(',') if item.strip()
}
PROPERTY_IMAGE_MAX_UPLOAD_BYTES = int(os.getenv('PROPERTY_IMAGE_MAX_UPLOAD_BYTES', str(5 * 1024 * 1024)))
PROPERTY_IMAGE_MAX_FILES_PER_UPLOAD = int(os.getenv('PROPERTY_IMAGE_MAX_FILES_PER_UPLOAD', '10'))
PROPERTY_IMAGE_MAX_FILES_PER_PROPERTY = int(os.getenv('PROPERTY_IMAGE_MAX_FILES_PER_PROPERTY', '30'))
