"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')
_default_secret_key = 'dev-only-change-me'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', _default_secret_key)

if not DEBUG and SECRET_KEY == _default_secret_key:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False."
    )

# SECURITY WARNING: don't run with debug turned on in production!
_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(',') if host.strip()]
if not ALLOWED_HOSTS:
    if DEBUG:
        # Safe local defaults so runserver/swagger work without manual env setup.
        ALLOWED_HOSTS = [
            "localhost",
            "127.0.0.1",
        ]
    else:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG=False."
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',                              # ← THÊM
    'rest_framework',
    'rest_framework_simplejwt',                 # ← THÊM
    'rest_framework_simplejwt.token_blacklist', # ← THÊM
    'drf_yasg',
    'django_filters',                           # ← THÊM
    'accounts',
    'properties',
    'appointments',
    'news',
    'prediction',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← THÊM, phải ĐẦU TIÊN
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_db_engine = os.getenv('HSW_DB_ENGINE', os.getenv('DB_ENGINE', 'django.db.backends.mysql')).strip()

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('HSW_DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('HSW_DB_NAME', os.getenv('DB_NAME', 'housesell_db')),
            # Use project-scoped vars first to avoid collisions with global OS vars.
            'USER': os.getenv('HSW_DB_USER', 'root'),
            'PASSWORD': os.getenv('HSW_DB_PASSWORD', ''),
            'HOST': os.getenv('HSW_DB_HOST', 'localhost'),
            'PORT': os.getenv('HSW_DB_PORT', '3306'),
        }
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # ← THÊM để Swagger nhận JWT/Session từ Admin
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/admin/login/'

from datetime import timedelta

# CORS - Cho phép FE (React) gọi API
_cors_allowed_origins = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080'
)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_allowed_origins.split(',') if origin.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _cors_allowed_origins.split(',') if origin.strip()]

SWAGGER_PUBLIC = os.getenv('SWAGGER_PUBLIC', 'true' if DEBUG else 'false').lower() in ('1', 'true', 'yes')

# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Media files (ảnh upload)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Property media upload policy (V8)
_property_image_allowed_types = os.getenv(
    'PROPERTY_IMAGE_ALLOWED_TYPES',
    'image/jpeg,image/png,image/webp,image/gif'
)
PROPERTY_IMAGE_ALLOWED_TYPES = {
    item.strip().lower() for item in _property_image_allowed_types.split(',') if item.strip()
}
PROPERTY_IMAGE_MAX_UPLOAD_BYTES = int(os.getenv('PROPERTY_IMAGE_MAX_UPLOAD_BYTES', str(5 * 1024 * 1024)))
PROPERTY_IMAGE_MAX_FILES_PER_UPLOAD = int(os.getenv('PROPERTY_IMAGE_MAX_FILES_PER_UPLOAD', '10'))
PROPERTY_IMAGE_MAX_FILES_PER_PROPERTY = int(os.getenv('PROPERTY_IMAGE_MAX_FILES_PER_PROPERTY', '30'))
