import json

def md(source): 
    return {"cell_type": "markdown", "metadata": {}, "source": source}
def code(source): 
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}

cells = []

# ── TITLE ─────────────────────────────────────────────────────────────────
cells.append(md([
"# 🏠 Dự Đoán Giá Nhà California — Linear Regression\n",
"**Nguồn dữ liệu:** [California Housing Prices](https://necromuralist.github.io/machine-learning-studies/posts/california-housing-prices/)  \n",
"**Mục tiêu:** Xây dựng mô hình hồi quy tuyến tính dự đoán `median_house_value` dựa trên các đặc trưng từ điều tra dân số California 1990.\n",
"\n---\n",
"## Mục Lục\n",
"1. Lý Thuyết Linear Regression\n",
"2. Cài Đặt & Import Thư Viện\n",
"3. Tải & Khám Phá Dữ Liệu (EDA)\n",
"4. Tiền Xử Lý Dữ Liệu\n",
"5. Xây Dựng & Huấn Luyện Mô Hình\n",
"6. Đánh Giá Mô Hình\n",
"7. Trực Quan Hóa Loss & Dự Đoán\n",
"8. Lưu & Tải Mô Hình\n",
"9. Kết Luận\n",
]))

# ── LY THUYET ─────────────────────────────────────────────────────────────
cells.append(md([
"## 1. Lý Thuyết Linear Regression\n",
"\n",
"### 1.1 Định Nghĩa\n",
"**Hồi quy tuyến tính (Linear Regression)** là thuật toán học có giám sát dự đoán giá trị liên tục, giả định mối quan hệ tuyến tính giữa $X$ và $y$.\n",
"\n",
"### 1.2 Hàm Giả Thuyết\n",
"$$\\hat{y} = \\theta_0 + \\theta_1 x_1 + \\cdots + \\theta_n x_n = \\mathbf{X}\\boldsymbol{\\theta}$$\n",
"\n",
"### 1.3 Hàm Mất Mát — MSE\n",
"$$\\mathcal{L} = \\frac{1}{m}\\sum_{i=1}^{m}(\\hat{y}^{(i)} - y^{(i)})^2$$\n",
"\n",
"### 1.4 Gradient Descent\n",
"$$\\theta_j := \\theta_j - \\alpha \\cdot \\frac{\\partial \\mathcal{L}}{\\partial \\theta_j}, \\quad \\frac{\\partial \\mathcal{L}}{\\partial \\theta_j} = \\frac{2}{m}\\sum_{i=1}^{m}(\\hat{y}^{(i)} - y^{(i)})x_j^{(i)}$$\n",
"\n",
"### 1.5 Normal Equation (Nghiệm Giải Tích)\n",
"$$\\boldsymbol{\\theta}^* = (\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{y}$$\n",
"\n",
"### 1.6 Các Chỉ Số Đánh Giá\n",
"| Chỉ số | Công thức | Ý nghĩa |\n",
"|--------|-----------|----------|\n",
"| MSE | $\\frac{1}{m}\\sum(\\hat{y}-y)^2$ | Sai số bình phương trung bình |\n",
"| RMSE | $\\sqrt{MSE}$ | Sai số cùng đơn vị với $y$ |\n",
"| MAE | $\\frac{1}{m}\\sum|\\hat{y}-y|$ | Sai số tuyệt đối trung bình |\n",
"| $R^2$ | $1-\\frac{SS_{res}}{SS_{tot}}$ | Tỷ lệ phương sai giải thích được |\n",
]))

# ── IMPORTS ────────────────────────────────────────────────────────────────
cells.append(md(["## 2. Import Thư Viện\n"]))
cells.append(code([
"# === IMPORTS & SETUP ===\n",
"import os\n",
"import warnings\n",
"import requests\n",
"import tarfile\n",
"import json\n",
"import joblib\n",
"\n",
"import numpy as np\n",
"import pandas as pd\n",
"import matplotlib.pyplot as plt\n",
"import matplotlib.ticker as mticker\n",
"import seaborn as sns\n",
"from scipy import stats as sc_stats\n",
"\n",
"from sklearn.model_selection import train_test_split, cross_val_score\n",
"from sklearn.preprocessing import StandardScaler\n",
"from sklearn.linear_model import LinearRegression, SGDRegressor\n",
"from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
"from sklearn.pipeline import Pipeline\n",
"\n",
"warnings.filterwarnings('ignore')\n",
"np.random.seed(42)\n",
"\n",
"# Tạo thư mục output ngay khi import\n",
"os.makedirs('plots',  exist_ok=True)\n",
"os.makedirs('models', exist_ok=True)\n",
"os.makedirs('data',   exist_ok=True)\n",
"\n",
"# Style\n",
"plt.rcParams.update({\n",
"    'figure.facecolor': '#0f0f1a',\n",
"    'axes.facecolor':   '#1a1a2e',\n",
"    'axes.edgecolor':   '#444',\n",
"    'axes.labelcolor':  '#e0e0e0',\n",
"    'xtick.color':      '#aaa',\n",
"    'ytick.color':      '#aaa',\n",
"    'text.color':       '#e0e0e0',\n",
"    'grid.color':       '#333',\n",
"    'grid.linestyle':   '--',\n",
"    'grid.alpha':       0.5,\n",
"})\n",
"PALETTE = ['#00d4ff', '#ff6b6b', '#7bed9f', '#ffa502', '#eccc68', '#a29bfe']\n",
"\n",
"print('Cac thu muc da duoc tao:')\n",
"for d in ['plots', 'models', 'data']:\n",
"    print(f'  {d}/ -> {os.path.abspath(d)}')\n",
"print('Thu vien import thanh cong!')\n",
]))

# ── TAI DU LIEU ─────────────────────────────────────────────────────────────
cells.append(md([
"## 3. Tai & Kham Pha Du Lieu (EDA)\n",
"\n",
"### 3.1 Nguon Du Lieu\n",
"Dataset California Housing 1990 Census voi **20,640 district**. Tai tu GitHub cua Aurelien Geron (cung nguon duoc tham chieu tai necromuralist.github.io).\n",
"\n",
"| Cot | Mo ta |\n",
"|-----|-------|\n",
"| `longitude` | Kinh do |\n",
"| `latitude` | Vi do |\n",
"| `housing_median_age` | Tuoi trung vi cua nha |\n",
"| `total_rooms` | Tong so phong |\n",
"| `total_bedrooms` | Tong so phong ngu (co missing) |\n",
"| `population` | Dan so district |\n",
"| `households` | So ho gia dinh |\n",
"| `median_income` | Thu nhap trung vi (don vi x$10k) |\n",
"| `median_house_value` | **Gia nha trung vi — TARGET** |\n",
"| `ocean_proximity` | Khoang cach den bien (categorical) |\n",
]))
cells.append(code([
"DATA_URL = 'https://github.com/ageron/handson-ml/raw/master/datasets/housing/housing.tgz'\n",
"DATA_TGZ = os.path.join('data', 'housing.tgz')\n",
"DATA_CSV = os.path.join('data', 'housing.csv')\n",
"\n",
"def fetch_housing_data():\n",
"    if not os.path.exists(DATA_CSV):\n",
"        print('Dang tai du lieu...')\n",
"        r = requests.get(DATA_URL, stream=True, timeout=60)\n",
"        with open(DATA_TGZ, 'wb') as f:\n",
"            for chunk in r.iter_content(chunk_size=1024):\n",
"                f.write(chunk)\n",
"        with tarfile.open(DATA_TGZ) as tf:\n",
"            tf.extractall('data')\n",
"        print('Tai xong!')\n",
"    else:\n",
"        print('File da ton tai, bo qua tai.')\n",
"\n",
"fetch_housing_data()\n",
"df = pd.read_csv(DATA_CSV)\n",
"print(f'Shape: {df.shape}')\n",
"df.head()\n",
]))
cells.append(code([
"print('=== Thong tin du lieu ===')\n",
"df.info()\n",
"print('\\n=== Thong ke mo ta ===')\n",
"df.describe().round(2)\n",
]))
cells.append(code([
"missing = df.isnull().sum()\n",
"print('=== Gia tri thieu ===')\n",
"print(missing[missing > 0])\n",
"print(f'\\nTy le thieu total_bedrooms: {df.total_bedrooms.isna().mean()*100:.2f}%')\n",
]))

# ── EDA PLOTS ────────────────────────────────────────────────────────────────
cells.append(md(["### 3.2 Phan Phoi Bien Muc Tieu\n"]))
cells.append(code([
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
"fig.suptitle('Phan phoi Median House Value', fontsize=15, fontweight='bold', color='#00d4ff')\n",
"\n",
"axes[0].hist(df['median_house_value'], bins=50, color='#00d4ff', alpha=0.8, edgecolor='#0a0a1a')\n",
"axes[0].set_title('Histogram')\n",
"axes[0].set_xlabel('Gia nha (USD)')\n",
"axes[0].set_ylabel('Tan suat')\n",
"axes[0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x:,.0f}'))\n",
"axes[0].grid(True)\n",
"\n",
"axes[1].hist(np.log1p(df['median_house_value']), bins=50, color='#ff6b6b', alpha=0.8, edgecolor='#0a0a1a')\n",
"axes[1].set_title('Histogram (Log Scale)')\n",
"axes[1].set_xlabel('log(Gia nha + 1)')\n",
"axes[1].grid(True)\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig('plots/01_target_distribution.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
"print(f'Gia nha trung vi: ${df[\"median_house_value\"].median():,.0f}')\n",
"print(f'Gia nha trung binh: ${df[\"median_house_value\"].mean():,.0f}')\n",
]))
cells.append(md(["### 3.3 Ban Do Dia Ly\n"]))
cells.append(code([
"fig, ax = plt.subplots(figsize=(12, 8))\n",
"sc = ax.scatter(\n",
"    df['longitude'], df['latitude'],\n",
"    c=df['median_house_value'], cmap='plasma',\n",
"    alpha=0.4, s=df['population']/100, linewidths=0\n",
")\n",
"cbar = plt.colorbar(sc, ax=ax)\n",
"cbar.set_label('Median House Value (USD)', color='#e0e0e0')\n",
"ax.set_title('Ban Do Gia Nha California\\n(kich thuoc=dan so, mau=gia nha)',\n",
"             fontsize=13, fontweight='bold', color='#00d4ff')\n",
"ax.set_xlabel('Kinh do')\n",
"ax.set_ylabel('Vi do')\n",
"ax.grid(True)\n",
"plt.tight_layout()\n",
"plt.savefig('plots/02_geo_map.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
]))
cells.append(md(["### 3.4 Ma Tran Tuong Quan\n"]))
cells.append(code([
"corr = df.drop(columns='ocean_proximity').corr()\n",
"fig, ax = plt.subplots(figsize=(12, 9))\n",
"mask = np.triu(np.ones_like(corr, dtype=bool))\n",
"sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',\n",
"            center=0, square=True, linewidths=0.5, ax=ax, annot_kws={'size': 9})\n",
"ax.set_title('Ma Tran Tuong Quan', fontsize=14, fontweight='bold', color='#00d4ff', pad=12)\n",
"plt.tight_layout()\n",
"plt.savefig('plots/03_correlation_matrix.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
"print('\\nTuong quan voi median_house_value:')\n",
"print(corr['median_house_value'].sort_values(ascending=False).to_string())\n",
]))
cells.append(md(["### 3.5 Ocean Proximity\n"]))
cells.append(code([
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
"vc = df['ocean_proximity'].value_counts()\n",
"axes[0].bar(vc.index, vc.values, color=PALETTE[:len(vc)])\n",
"axes[0].set_title('So luong theo Ocean Proximity')\n",
"axes[0].set_ylabel('Count'); axes[0].grid(True, axis='y')\n",
"\n",
"grp = df.groupby('ocean_proximity')['median_house_value'].median().sort_values(ascending=False)\n",
"axes[1].bar(grp.index, grp.values, color=PALETTE[:len(grp)])\n",
"axes[1].set_title('Gia nha trung vi theo Ocean Proximity')\n",
"axes[1].set_ylabel('Median House Value')\n",
"axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x:,.0f}'))\n",
"axes[1].grid(True, axis='y')\n",
"plt.suptitle('Phan Tich Ocean Proximity', fontsize=13, fontweight='bold', color='#00d4ff')\n",
"plt.tight_layout()\n",
"plt.savefig('plots/04_ocean_proximity.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
]))

# ── TIEN XU LY ──────────────────────────────────────────────────────────────
cells.append(md([
"## 4. Tien Xu Ly Du Lieu\n",
"\n",
"| Buoc | Van de | Giai phap |\n",
"|------|--------|----------|\n",
"| 1 | Missing values (total_bedrooms) | Dien bang median |\n",
"| 2 | Categorical (ocean_proximity) | One-Hot Encoding |\n",
"| 3 | Feature Engineering | Tao 3 features moi |\n",
"| 4 | Scale lech | StandardScaler |\n",
"| 5 | Chia tap | Train 70 / Val 15 / Test 15 |\n",
]))
cells.append(code([
"df_proc = df.copy()\n",
"\n",
"# Dien missing\n",
"med_bed = df_proc['total_bedrooms'].median()\n",
"df_proc['total_bedrooms'].fillna(med_bed, inplace=True)\n",
"print(f'Dien missing total_bedrooms = {med_bed}')\n",
"\n",
"# Feature Engineering\n",
"df_proc['rooms_per_household']      = df_proc['total_rooms']    / df_proc['households']\n",
"df_proc['bedrooms_per_room']        = df_proc['total_bedrooms'] / df_proc['total_rooms']\n",
"df_proc['population_per_household'] = df_proc['population']     / df_proc['households']\n",
"print('Feature Engineering: 3 features moi da duoc tao')\n",
"\n",
"# One-Hot Encoding\n",
"df_proc = pd.get_dummies(df_proc, columns=['ocean_proximity'], drop_first=False)\n",
"ocean_cols = [c for c in df_proc.columns if 'ocean_proximity' in c]\n",
"print('One-Hot cols:', ocean_cols)\n",
]))
cells.append(code([
"TARGET = 'median_house_value'\n",
"X = df_proc.drop(columns=[TARGET])\n",
"y = df_proc[TARGET]\n",
"print(f'Features: {X.shape[1]} | Samples: {len(X)}')\n",
"print(list(X.columns))\n",
]))
cells.append(code([
"# Chia Train / Val / Test (70 / 15 / 15)\n",
"X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.15, random_state=42)\n",
"X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1765, random_state=42)\n",
"\n",
"print('=== Phan chia tap du lieu ===')\n",
"print(f'Train:      {X_train.shape[0]:>6} mau ({X_train.shape[0]/len(X)*100:.1f}%)')\n",
"print(f'Validation: {X_val.shape[0]:>6} mau ({X_val.shape[0]/len(X)*100:.1f}%)')\n",
"print(f'Test:       {X_test.shape[0]:>6} mau ({X_test.shape[0]/len(X)*100:.1f}%)')\n",
]))
cells.append(code([
"scaler = StandardScaler()\n",
"X_train_s = scaler.fit_transform(X_train)\n",
"X_val_s   = scaler.transform(X_val)\n",
"X_test_s  = scaler.transform(X_test)\n",
"print('Chuan hoa StandardScaler hoan tat!')\n",
"print(f'Mean (3 features dau): {X_train_s.mean(axis=0)[:3].round(4)}')\n",
"print(f'Std  (3 features dau): {X_train_s.std(axis=0)[:3].round(4)}')\n",
]))

# ── TRAIN ────────────────────────────────────────────────────────────────────
cells.append(md([
"## 5. Xay Dung & Huan Luyen Mo Hinh\n",
"\n",
"### 5.1 Sklearn LinearRegression (Normal Equation)\n",
"Sklearn dung phuong phap SVD giai truc tiep nghiem toi uu.\n",
]))
cells.append(code([
"lr_model = LinearRegression()\n",
"lr_model.fit(X_train_s, y_train)\n",
"\n",
"y_pred_train_lr = lr_model.predict(X_train_s)\n",
"y_pred_val_lr   = lr_model.predict(X_val_s)\n",
"\n",
"mse_train = mean_squared_error(y_train, y_pred_train_lr)\n",
"mse_val   = mean_squared_error(y_val,   y_pred_val_lr)\n",
"\n",
"print('=== Sklearn LinearRegression ===')\n",
"print(f'Train | MSE: {mse_train:>14,.2f} | RMSE: {np.sqrt(mse_train):>10,.2f} | R2: {r2_score(y_train, y_pred_train_lr):.4f}')\n",
"print(f'Val   | MSE: {mse_val:>14,.2f} | RMSE: {np.sqrt(mse_val):>10,.2f} | R2: {r2_score(y_val, y_pred_val_lr):.4f}')\n",
]))
cells.append(md(["### 5.2 Gradient Descent Thu Cong (NumPy)\nLap trinh tay Mini-Batch GD voi Early Stopping de hieu ro co che cap nhat tham so.\n"]))
cells.append(code([
"class LinearRegressionGD:\n",
"    def __init__(self, lr=0.01, n_epochs=200, batch_size=256, patience=20):\n",
"        self.lr=lr; self.n_epochs=n_epochs\n",
"        self.batch_size=batch_size; self.patience=patience\n",
"        self.train_losses=[]; self.val_losses=[]\n",
"\n",
"    def fit(self, X, y, X_val=None, y_val=None):\n",
"        m, n = X.shape\n",
"        self.W = np.zeros(n); self.b = 0.0\n",
"        best_val, no_imp = np.inf, 0\n",
"        self.best_W, self.best_b = self.W.copy(), self.b\n",
"\n",
"        for epoch in range(1, self.n_epochs+1):\n",
"            idx = np.random.permutation(m)\n",
"            Xs, ys = X[idx], y[idx]\n",
"            for s in range(0, m, self.batch_size):\n",
"                Xb, yb = Xs[s:s+self.batch_size], ys[s:s+self.batch_size]\n",
"                err = Xb@self.W + self.b - yb\n",
"                nb = len(yb)\n",
"                self.W -= self.lr*(2/nb)*(Xb.T@err)\n",
"                self.b -= self.lr*(2/nb)*err.sum()\n",
"\n",
"            tl = np.mean((X@self.W+self.b - y)**2)\n",
"            self.train_losses.append(tl)\n",
"\n",
"            if X_val is not None:\n",
"                vl = np.mean((X_val@self.W+self.b - y_val)**2)\n",
"                self.val_losses.append(vl)\n",
"                if vl < best_val:\n",
"                    best_val=vl; no_imp=0\n",
"                    self.best_W=self.W.copy(); self.best_b=self.b\n",
"                else:\n",
"                    no_imp+=1\n",
"                if no_imp >= self.patience:\n",
"                    print(f'  Early stopping tai epoch {epoch}')\n",
"                    break\n",
"\n",
"            if epoch % 20 == 0:\n",
"                msg = f'Epoch {epoch:>4}/{self.n_epochs} | Train MSE: {tl:>12,.2f}'\n",
"                if X_val is not None: msg += f' | Val MSE: {vl:>12,.2f}'\n",
"                print(msg)\n",
"\n",
"        self.W, self.b = self.best_W, self.best_b\n",
"        return self\n",
"\n",
"    def predict(self, X):\n",
"        return X@self.W + self.b\n",
"\n",
"print('Class LinearRegressionGD dinh nghia xong!')\n",
]))
cells.append(code([
"gd_model = LinearRegressionGD(lr=0.05, n_epochs=300, batch_size=512, patience=20)\n",
"gd_model.fit(X_train_s, y_train.values, X_val=X_val_s, y_val=y_val.values)\n",
"\n",
"y_pred_val_gd = gd_model.predict(X_val_s)\n",
"mse_vl_gd = mean_squared_error(y_val, y_pred_val_gd)\n",
"\n",
"print('\\n=== LinearRegressionGD ===')\n",
"print(f'Val | MSE: {mse_vl_gd:>14,.2f} | RMSE: {np.sqrt(mse_vl_gd):>10,.2f} | R2: {r2_score(y_val, y_pred_val_gd):.4f}')\n",
]))
cells.append(md(["### 5.3 SGDRegressor (Sklearn)\n"]))
cells.append(code([
"sgd_model = SGDRegressor(\n",
"    max_iter=1000, tol=1e-4, learning_rate='invscaling',\n",
"    eta0=0.01, random_state=42,\n",
"    early_stopping=True, validation_fraction=0.15, n_iter_no_change=20\n",
")\n",
"sgd_model.fit(X_train_s, y_train)\n",
"y_pred_val_sgd = sgd_model.predict(X_val_s)\n",
"mse_sgd = mean_squared_error(y_val, y_pred_val_sgd)\n",
"r2_sgd  = r2_score(y_val, y_pred_val_sgd)\n",
"print(f'SGDRegressor Val | MSE: {mse_sgd:>12,.2f} | RMSE: {np.sqrt(mse_sgd):>10,.2f} | R2: {r2_sgd:.4f}')\n",
"print(f'So vong lap: {sgd_model.n_iter_}')\n",
]))

# ── DANH GIA ─────────────────────────────────────────────────────────────────
cells.append(md(["## 6. Danh Gia Mo Hinh\n### 6.1 Cross-Validation (5-Fold)\n"]))
cells.append(code([
"pipe = Pipeline([('sc', StandardScaler()), ('lr', LinearRegression())])\n",
"cv  = cross_val_score(pipe, X, y, cv=5, scoring='neg_mean_squared_error')\n",
"cv_rmse = np.sqrt(-cv)\n",
"print('=== 5-Fold CV RMSE ===')\n",
"for i, v in enumerate(cv_rmse, 1):\n",
"    print(f'  Fold {i}: {v:>10,.2f}')\n",
"print(f'  Mean : {cv_rmse.mean():>10,.2f}')\n",
"print(f'  Std  : {cv_rmse.std():>10,.2f}')\n",
]))
cells.append(md(["### 6.2 Bang So Sanh 3 Mo Hinh\n"]))
cells.append(code([
"y_pred_test = lr_model.predict(X_test_s)\n",
"test_mse  = mean_squared_error(y_test, y_pred_test)\n",
"test_rmse = np.sqrt(test_mse)\n",
"test_mae  = mean_absolute_error(y_test, y_pred_test)\n",
"test_r2   = r2_score(y_test, y_pred_test)\n",
"\n",
"rows = [\n",
"    ['LinearRegression (NE)',\n",
"     f'{np.sqrt(mse_val):,.2f}', f'{mean_absolute_error(y_val, y_pred_val_lr):,.2f}',\n",
"     f'{r2_score(y_val, y_pred_val_lr):.4f}'],\n",
"    ['LinearRegressionGD',\n",
"     f'{np.sqrt(mse_vl_gd):,.2f}', f'{mean_absolute_error(y_val, y_pred_val_gd):,.2f}',\n",
"     f'{r2_score(y_val, y_pred_val_gd):.4f}'],\n",
"    ['SGDRegressor',\n",
"     f'{np.sqrt(mse_sgd):,.2f}', f'{mean_absolute_error(y_val, y_pred_val_sgd):,.2f}',\n",
"     f'{r2_sgd:.4f}'],\n",
"]\n",
"df_cmp = pd.DataFrame(rows, columns=['Mo hinh','Val RMSE','Val MAE','Val R2'])\n",
"print('=== So sanh tren Validation Set ===')\n",
"print(df_cmp.to_string(index=False))\n",
"print(f'\\n=== TEST SET (LinearRegression) ===')\n",
"print(f'MSE  : {test_mse:>15,.2f}')\n",
"print(f'RMSE : {test_rmse:>15,.2f} USD')\n",
"print(f'MAE  : {test_mae:>15,.2f} USD')\n",
"print(f'R2   : {test_r2:>15.4f}')\n",
]))
cells.append(md(["### 6.3 Feature Importance (He So Hoi Quy)\n"]))
cells.append(code([
"feat_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': lr_model.coef_})\n",
"feat_df['Abs'] = feat_df['Coefficient'].abs()\n",
"feat_df = feat_df.sort_values('Abs', ascending=True).reset_index(drop=True)\n",
"\n",
"fig, ax = plt.subplots(figsize=(11, 7))\n",
"colors = ['#00d4ff' if c > 0 else '#ff6b6b' for c in feat_df['Coefficient']]\n",
"ax.barh(feat_df['Feature'], feat_df['Coefficient'], color=colors)\n",
"ax.axvline(0, color='white', lw=0.8)\n",
"ax.set_title('He So Hoi Quy (Feature Importance)', fontsize=13, fontweight='bold', color='#00d4ff')\n",
"ax.set_xlabel('Coefficient')\n",
"ax.grid(True, axis='x')\n",
"plt.tight_layout()\n",
"plt.savefig('plots/05_coefficients.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
]))

# ── PLOTS ─────────────────────────────────────────────────────────────────────
cells.append(md(["## 7. Truc Quan Hoa Loss & Du Doan\n### 7.1 Learning Curves (Gradient Descent)\n"]))
cells.append(code([
"ep = range(1, len(gd_model.train_losses)+1)\n",
"fig, axes = plt.subplots(1, 2, figsize=(15, 5))\n",
"fig.suptitle('Learning Curves - LinearRegressionGD', fontsize=13, fontweight='bold', color='#00d4ff')\n",
"\n",
"axes[0].plot(ep, gd_model.train_losses, color='#00d4ff', label='Train MSE')\n",
"axes[0].plot(ep, gd_model.val_losses,   color='#ff6b6b', label='Val MSE', ls='--')\n",
"axes[0].set_title('MSE Loss theo Epoch'); axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('MSE')\n",
"axes[0].legend(); axes[0].grid(True)\n",
"\n",
"axes[1].plot(ep, np.sqrt(gd_model.train_losses), color='#7bed9f', label='Train RMSE')\n",
"axes[1].plot(ep, np.sqrt(gd_model.val_losses),   color='#ffa502', label='Val RMSE', ls='--')\n",
"axes[1].set_title('RMSE theo Epoch'); axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('RMSE (USD)')\n",
"axes[1].legend(); axes[1].grid(True)\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig('plots/06_learning_curves.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
"print(f'Train RMSE cuoi: {np.sqrt(gd_model.train_losses[-1]):,.2f} | Val RMSE cuoi: {np.sqrt(gd_model.val_losses[-1]):,.2f}')\n",
]))
cells.append(md(["### 7.2 Du Doan vs Thuc Te\n"]))
cells.append(code([
"fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n",
"fig.suptitle('Du Doan vs Thuc Te - Tap Test', fontsize=13, fontweight='bold', color='#00d4ff')\n",
"pairs = [(y_pred_test, 'LinearRegression (NE)'),\n",
"         (gd_model.predict(X_test_s), 'LinearRegressionGD')]\n",
"for ax, (preds, title) in zip(axes, pairs):\n",
"    ax.scatter(y_test, preds, alpha=0.2, s=5, color='#00d4ff')\n",
"    mn, mx = y_test.min(), y_test.max()\n",
"    ax.plot([mn, mx], [mn, mx], 'r--', lw=1.5, label='Perfect')\n",
"    ax.set_title(title); ax.set_xlabel('Gia thuc te (USD)'); ax.set_ylabel('Gia du doan (USD)')\n",
"    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1e3:.0f}k'))\n",
"    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1e3:.0f}k'))\n",
"    ax.legend(); ax.grid(True)\n",
"plt.tight_layout()\n",
"plt.savefig('plots/07_pred_vs_actual.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
]))
cells.append(md(["### 7.3 Phan Tich Residuals\n"]))
cells.append(code([
"residuals = y_test.values - y_pred_test\n",
"fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
"fig.suptitle('Phan Tich Residuals', fontsize=13, fontweight='bold', color='#00d4ff')\n",
"\n",
"axes[0].scatter(y_pred_test, residuals, alpha=0.2, s=5, color='#a29bfe')\n",
"axes[0].axhline(0, color='#ff6b6b', lw=1.5)\n",
"axes[0].set_title('Residuals vs Predicted'); axes[0].set_xlabel('Du doan'); axes[0].set_ylabel('Residual'); axes[0].grid(True)\n",
"\n",
"axes[1].hist(residuals, bins=60, color='#00d4ff', alpha=0.8, edgecolor='#0a0a1a')\n",
"axes[1].set_title('Phan phoi Residuals'); axes[1].set_xlabel('Residual'); axes[1].grid(True)\n",
"\n",
"(osm, osr), (slope, intercept, r) = sc_stats.probplot(residuals, dist='norm')\n",
"axes[2].scatter(osm, osr, s=5, color='#7bed9f', alpha=0.5)\n",
"axes[2].plot([min(osm), max(osm)], [slope*min(osm)+intercept, slope*max(osm)+intercept], 'r--')\n",
"axes[2].set_title('Q-Q Plot'); axes[2].set_xlabel('Theo ly'); axes[2].set_ylabel('Thuc te'); axes[2].grid(True)\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig('plots/08_residuals.png', dpi=150, bbox_inches='tight')\n",
"plt.show()\n",
"print(f'Residuals Mean: {residuals.mean():,.2f} | Std: {residuals.std():,.2f}')\n",
]))

# ── SAVE MODEL ────────────────────────────────────────────────────────────────
cells.append(md([
"## 8. Luu & Tai Mo Hinh\n",
"### 8.1 Luu Pipeline (Scaler + Model)\n",
"Luu toan bo pipeline duoi dang `.joblib` de tranh data leakage khi deploy.\n",
]))
cells.append(code([
"# Luu sklearn pipeline\n",
"final_pipeline = Pipeline([('scaler', scaler), ('lr', lr_model)])\n",
"joblib.dump(final_pipeline, 'models/lr_pipeline.joblib')\n",
"print('Da luu: models/lr_pipeline.joblib')\n",
"\n",
"# Luu GD model\n",
"gd_params = {\n",
"    'W': gd_model.W, 'b': gd_model.b,\n",
"    'feature_names': X.columns.tolist(),\n",
"    'scaler_mean': scaler.mean_, 'scaler_std': scaler.scale_\n",
"}\n",
"joblib.dump(gd_params, 'models/lr_gd_params.joblib')\n",
"print('Da luu: models/lr_gd_params.joblib')\n",
"\n",
"for fp in ['models/lr_pipeline.joblib', 'models/lr_gd_params.joblib']:\n",
"    print(f'  {fp}: {os.path.getsize(fp)/1024:.1f} KB')\n",
]))
cells.append(md(["### 8.2 Tai & Kiem Tra Mo Hinh\n"]))
cells.append(code([
"loaded_pipe = joblib.load('models/lr_pipeline.joblib')\n",
"\n",
"sample_idx = np.random.choice(len(X_test), 5, replace=False)\n",
"X_sample   = X_test.iloc[sample_idx]\n",
"y_sample   = y_test.iloc[sample_idx]\n",
"y_pred_s   = loaded_pipe.predict(X_sample)\n",
"\n",
"print(f'{'Index':>8} | {\"Thuc te\":>14} | {\"Du doan\":>14} | {\"Sai so\":>12}')\n",
"print('-'*55)\n",
"for i, (a, p) in enumerate(zip(y_sample, y_pred_s)):\n",
"    print(f'{sample_idx[i]:>8} | ${a:>13,.0f} | ${p:>13,.0f} | ${abs(a-p):>11,.0f}')\n",
"print(f'\\nMo hinh load thanh cong! R2 = {r2_score(y_sample, y_pred_s):.4f}')\n",
]))

# ── KET LUAN ──────────────────────────────────────────────────────────────────
cells.append(md(["## 9. Ket Luan\n"]))
cells.append(code([
"print('='*60)\n",
"print('       KET QUA CUOI CUNG TREN TAP TEST')\n",
"print('='*60)\n",
"print(f'  MSE  : {test_mse:>15,.2f}')\n",
"print(f'  RMSE : {test_rmse:>15,.2f} USD')\n",
"print(f'  MAE  : {test_mae:>15,.2f} USD')\n",
"print(f'  R2   : {test_r2:>15.4f}')\n",
"print('='*60)\n",
"print(f'Mo hinh giai thich duoc {test_r2*100:.1f}% phuong sai cua gia nha.')\n",
"print(f'Sai so trung binh moi du doan: ~${test_mae:,.0f}')\n",
]))
cells.append(md([
"### Nhan Xet & Huong Cai Thien\n",
"\n",
"| Van de | Giai phap |\n",
"|--------|-----------|\n",
"| Gia nha bi cap o \\$500K | Loai mau outlier nay |\n",
"| Quan he khong tuyen tinh hoan toan | Polynomial Features, Ridge/Lasso |\n",
"| Outliers trong population, rooms | RobustScaler, Winsorization |\n",
"| Linear Regression la baseline | RandomForest, XGBoost, Neural Net |\n",
"\n",
"### Cau Truc Thu Muc\n",
"```\n",
"LinearRegression/\n",
"├── data/housing.csv\n",
"├── models/lr_pipeline.joblib\n",
"├── models/lr_gd_params.joblib\n",
"└── plots/ (8 bieu do PNG)\n",
"```\n",
"*Nguon du lieu: necromuralist.github.io & github.com/ageron/handson-ml*\n",
]))

# ── BUILD ─────────────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4, "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}
with open('LinearRegression_HoiQuy_GiaNha.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Notebook da duoc tao lai: LinearRegression_HoiQuy_GiaNha.ipynb')
print(f'Tong so cells: {len(cells)}')
